
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-06
owner: ucsb-cs156-f25
repo_name: team01-f25-06
pull_requests: [{"author":{"id":"U_kgDOCeQtvw","is_bot":false,"login":"Helenlongjiao","name":"Longjiao Chen"},"headRefName":"ucsbdiningcommonsmenuitem-controller","number":51,"title":"Add backend controller and tests for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/51"},{"author":{"id":"U_kgDOCeQtvw","is_bot":false,"login":"Helenlongjiao","name":"Longjiao Chen"},"headRefName":"configure-admin-emails","number":50,"title":"Configure APP_ADMIN_EMAILS to include all instructors and teammates","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/50"},{"author":{"id":"U_kgDOB2QqkQ","is_bot":false,"login":"jml557","name":"Julia L"},"headRefName":"jml-MenuItemReview-create-db","number":49,"title":"jml - create database table for MenuItemReviews","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/49"},{"author":{"id":"U_kgDOCeQtvw","is_bot":false,"login":"Helenlongjiao","name":"Longjiao Chen"},"headRefName":"helenlongjiao","number":48,"title":"Add UCSBDiningCommonsMenuItem entity and repository","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/48"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-articles-delete","number":47,"title":"NF - Articles database DELETE functionality + tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/47"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-articles-put","number":46,"title":"NF - Articles database PUT functionality + tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/46"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-articles-get-by-id","number":45,"title":"NF -  Articles database GET (by ID) functionality + tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/45"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-create-commit-controller","number":44,"title":"NF - Articles database commit controller, adding the GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/44"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-articles-create-db","number":43,"title":"NF - Articles database table created","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/43"}]
