
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-06
owner: ucsb-cs156-f25
repo_name: team01-f25-06
pull_requests: [{"author":{"id":"U_kgDOCVy2iQ","is_bot":false,"login":"AbhiramA02","name":""},"headRefName":"aa-create-RecommendationRequest-controller","number":63,"title":"aa - create recommendation request controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/63"},{"author":{"id":"U_kgDOCeQtvw","is_bot":false,"login":"Helenlongjiao","name":"Longjiao Chen"},"headRefName":"configure-admin-emails","number":50,"title":"Configure APP_ADMIN_EMAILS to include all instructors and teammates","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/50"}]
