
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-06
owner: ucsb-cs156-f25
repo_name: team01-f25-06
pull_requests: [{"author":{"id":"U_kgDOCMvu0g","is_bot":false,"login":"austinchan3678","name":""},"headRefName":"austin/organization-controller","number":62,"title":"austin - add UCSBOrganizationController and endpoints for Get (all) and Post","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/62"},{"author":{"id":"U_kgDOB2QqkQ","is_bot":false,"login":"jml557","name":"Julia L"},"headRefName":"jml-MenuItemReview-add-put-endpoint","number":61,"title":"jml - MenuItemReview add PUT controller endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/61"},{"author":{"id":"U_kgDOCVy2iQ","is_bot":false,"login":"AbhiramA02","name":""},"headRefName":"aa-RecommendationRequest-create-db","number":60,"title":"aa - create database table for recommendation requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/60"},{"author":{"id":"U_kgDOB2QqkQ","is_bot":false,"login":"jml557","name":"Julia L"},"headRefName":"jml-MenuItemReview-add-get-endpoint","number":59,"title":"jml - MenuItemReview, add get by id endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/59"},{"author":{"id":"U_kgDOB2QqkQ","is_bot":false,"login":"jml557","name":"Julia L"},"headRefName":"jml-MenuItemReview-create-controller","number":57,"title":"jml - implemented MenuItemReviews controller get & post, and relevant…","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/57"},{"author":{"id":"U_kgDOCeQtvw","is_bot":false,"login":"Helenlongjiao","name":"Longjiao Chen"},"headRefName":"configure-admin-emails","number":50,"title":"Configure APP_ADMIN_EMAILS to include all instructors and teammates","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/50"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-articles-delete","number":47,"title":"NF - Articles database DELETE functionality + tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/47"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-articles-put","number":46,"title":"NF - Articles database PUT functionality + tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/46"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-articles-get-by-id","number":45,"title":"NF -  Articles database GET (by ID) functionality + tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-06/pull/45"}]
